- uses: Platane/snk/svg-only@v2
  with:
    github_user_name: ${{fatalcr-git}}

    outputs: |
      dist/github-snake.svg
      dist/github-snake-dark.svg?palette=github-dark

  env:

    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
